### ISSUE TITLE
Errors patching Bricade Horrors

### ISSUE THREAD

**Issue by poskass** [DerekPascarella/BirdcageOfHorrors-EnglishPatchDreamcast#1]
The Selected DCP patch file contain instructions to modify files not present on the selected source disc image. Patching process can't  proceed. Disc 1 Bricade Horrors has md5 b3ecdf113fd42344dd84142679e4cb36

**Comment by DerekPascarella** [comment]
I see the .gdi table-of-contents file has the same MD5 hash, but that doesn't necessarily mean it's the correct image.

You must also ensure that you're using the "Chapter 1" DCP patch file with the correct disc. That error message suggests you're attempting to patch the wrong disc with the wrong DCP patch file.

Can you verify that you're using `Birdcage.of.Horrors.-.Chapter.1.-.Contract.English.v1.0.dcp` with the following GDI?

```
b3ecdf113fd42344dd84142679e4cb36  Grauen no Torikago - Kapitel 1 - Keiyaku v1.003 (1999)(Sega)(JP)[!].gdi
d7f5989b393d0b9dcd99b995192ac1b9  track01.bin
d09be539a7074a058159505b7f5fdcb3  track02.raw
4f7cef0f61644ce6ad7b7bf89b0fdb28  track03.bin
```

The Redump CUE/BIN format is also supported. That release has MD5s that look like this:

```
236494c27e5279b626a477cc2523bcdb  Grauen no Torikago - Kapitel 1 - Keiyaku (Japan).cue
d7f5989b393d0b9dcd99b995192ac1b9  Grauen no Torikago - Kapitel 1 - Keiyaku (Japan) (Track 1).bin
652a31166a58b8f933e8a924e7c88780  Grauen no Torikago - Kapitel 1 - Keiyaku (Japan) (Track 2).bin
4f7cef0f61644ce6ad7b7bf89b0fdb28  Grauen no Torikago - Kapitel 1 - Keiyaku (Japan) (Track 3).bin
```

Both of these rips (as mentioned in the README) are compatible. You may be using an unsupported rip, or simply applying the wrong disc (e.g., attempting to apply the "Chapter 2" DCP patch to the "Chapter 1" GDI).

Also, can you please let me know what operating system you're running with the patcher? It's possible that one or more helper utilities inside of the "tools" folder is being erroneously blocked by your anti-virus software. However, the patcher does a sanity check upon launch to ensure all of those tools are present. If anti-virus is to blame, it would at least seem that none of the helper utilities are being deleted.

**Comment by poskass** [comment]
Ok, second attempt, now I have checked that the gdi image and the dcp file are correct and I get the following error "The select DCP patch file is either corrupt or imcompatible". I will try to find another image. I am using Win10 and the antivirus has not blocked anything, I have that folder in an exception.

**Comment by DerekPascarella** [comment]
Try right-clicking all the EXEs and DLLs in the "tools" folder, then select Properties. Ensure none show the "Blocked" check mark at the bottom-right.

Also, pleasure ensure you're on the latest version of the patcher. You can also try running the patcher as administrator to see if that changes the behavior at all.

It's also worth comparing the MD5s of your DCPs with the following to be sure they were downloaded correctly:

```
030371bc06f7715b024e1c36a66237aa  Birdcage of Horrors - Chapter 1 - Contract (English v1.0).dcp
112bed6e0507a6f9d3535a0e1776e2da  Birdcage of Horrors - Chapter 2 - Birdcage (English v1.0).dcp
2aa7cfa8a527e40194093834efa627e0  Birdcage of Horrors - Chapter 3 - Completion (English v1.0).dcp
2bd2f7c5821c45c6ce3dda115cd77ab2  Birdcage of Horrors - Chapter 4 - Encounter (English v1.0).dcp
61b80c80a5a266d62a5c50e6f00bb6d3  Birdcage of Horrors - Chapter 5 - Atonement (English v1.0).dcp
09d19c32feada443a63db78a35dbc94c  Birdcage of Horrors - Chapter 6 - Tremor (English v1.0).dcp
```

Furthermore, these are the MD5s of all the helper utilities in the "tools" folder:

```
4c74019b91394ad86152bb0a7d529e68  bin2iso.exe
ffe0c672222c3e1fae74de7055676971  buildgdi.exe
e2bbf1d77f2f1c5736bc95030c2954f3  convertredumptogdi.exe
87b9a36f5f2bf5051dbb74cb4a50dce8  DiscUtils.dll
83ad2adff26b33b7a7eaa61b01460662  extract.exe
12d3a5f20d8c37f194381321aedeac52  gditools.exe
5ec82a218d60f97f85f33478ca1ab9f4  python27.dll
7ac21750e2032e5aeb681ac88460bdce  xdelta.exe
```

Lastly, these are the MD5s of the patcher's executables:

```
3a3cb537db4e6e006c7b561d9d509670  Universal Dreamcast Patch Builder.exe
6c4c536e2b7a033aa3decf176b74dc66  Universal Dreamcast Patcher.exe
```

**Comment by poskass** [comment]
Thanks, I will check all the files, thanks. I will let you know tomorrow if I have succeeded.

**Comment by DerekPascarella** [comment]
If you still have issues after that, please contact me via email, Discord, or Twitter (links are on https://dreamcastforever.com). I will assist further.

**Comment by poskass** [comment]
Hi Derek, I have not been able to patch the files, I have tried several combinations as you told me. Don't worry, I have already found a place where I can play it, thanks for your time.

**Comment by DerekPascarella** [comment]
I wish I knew why my patching utility is behaving on your setup. It's a tool that has been used literally hundreds (maybe thousands?) of times by many different users, which is what's helped me work out all of the old bugs.

That said, I'm glad you found copies you can use 🙂

I will close this issue thread.

**Comment by DerekPascarella** [comment]
I wish I knew why my patching utility is behaving on your setup. It's a tool that has been used literally hundreds (maybe thousands?) of times by many different users, which is what's helped me work out all of the old bugs.

That said, I'm glad you found copies you can use 🙂

I will close this issue thread.
