### ISSUE TITLE
Bug report (typos)

### ISSUE THREAD

**Issue by Knochy** [DerekPascarella/BirdcageOfHorrors-EnglishPatchDreamcast#11]
Hello DerekPascarella!
While watching Birdcage of Horrors I noticed some spelling mistakes and wanted to bring them to your attention.

They are at:
Disc 03 Track 56 - 00:39 (Nao is referred to as Noa)
Disc 06 Track 11 - 00:39 (Instead of leaving the subtitles say "leavening")

I hope this information helped you.

**Comment by DerekPascarella** [comment]
Thank you very much for reporting these. It seems impossible to find every typo myself, haha.

I guess I'll eventually be doing a v1.2 release, though certainly I'll be waiting a while for additional typo submissions.

**Comment by Knochy** [comment]
Aside from the ones I already mentioned, I only noticed 2 more typos, which were somewhere before Disc 03 Track 56. 
(I'm sorry because I don't know where they were exactly)
I think those are all leftover typos in the entire series.

**Comment by DerekPascarella** [comment]
@Knochy when you say "before disc 3 track 56", do you mean the other typos _are on_ disc 3?

**Comment by Knochy** [comment]
No, I mean all tracks before that (also the ones on Disc 1 and 2).

**Comment by Knochy** [comment]
@DerekPascarella I found the typos! I rewatched Disc 1 and found both of them. 
They are at:
Disc 01 Track 15 - 00:15 ("the" in the second sentence is capitalized)
Disc 01 Track 54 - 00:56 (Instead of "That's" the subtitles say "Thats's")

**Comment by DerekPascarella** [comment]
Excellent, thank you @Knochy 🙂

**Comment by Knochy** [comment]
You're welcome, and I appreciate your work.

**Comment by privateye** [comment]
**Chapter 2 - Contract**

- _"Buy why?"_
"Buy" should be "But"
https://www.youtube.com/watch?v=298di50zsHg&t=3659s

**Chapter 3 - Trap**

- _"Well, compared to before, there's on less person among us here."_
"on" should be "one"
https://www.youtube.com/watch?v=1RpPw1FFF_I&t=117s

- _"Why are two still snooping around!?"_
Is this supposed to be "Why are you two still snooping around!?" in reference to Nao and Tetsu?
https://www.youtube.com/watch?v=1RpPw1FFF_I&t=292s

**Chapter 4 - Encounter**

* _"did Mr. Takamura every talk to you about his childhood?"_
"every" should be "ever"
https://www.youtube.com/watch?v=CTXC4xM1r_M&t=2104s

* _"I had no choice... I need to pay back them back."_
Should be "I had no choice... I need to pay them back."
https://www.youtube.com/watch?v=CTXC4xM1r_M&t=3906s

**Chapter 5 - Atonement**

- _"But why."_
Should be "But why?"
https://www.youtube.com/watch?v=hy5-MEbs6AU&t=854s

- _"Or will she be dead."_
Should be "Or will she be dead?"
https://www.youtube.com/watch?v=hy5-MEbs6AU&t=2399s

- _"And it also fits nicely with Ms. Katase's confession on that tape."_
"Ms." should be "Mr."
https://www.youtube.com/watch?v=hy5-MEbs6AU&t=2478s

- _"Did you find a murder that fits Ms. Katase's confession?"_
"Ms." should be "Mr."
https://www.youtube.com/watch?v=hy5-MEbs6AU&t=2482s

**Chapter 6 - Tremor**

- _"I think that if accepted this money"_
Should be "I think that if I accepted this money"
https://www.youtube.com/watch?v=S9-RqcyzcwI&t=1155s

**Comment by DerekPascarella** [comment]
Thanks @privateye.

**Comment by DerekPascarella** [comment]
Okay, all of these typos have been fixed. I believe I'll wait a while longer before pushing a v1.2 release though.
