### ISSUE TITLE
Bad timings

### ISSUE THREAD

**Issue by dante3732** [DerekPascarella/BirdcageOfHorrors-EnglishPatchDreamcast#12]
Good day, in many places bad timing, should have tried to do no more than 20 characters per second, subtitles have this designation by default in subtitle edit netfilx english mode. I have to pause it to have time to read it.

Also you have a possibility to make a patch to convert video to mp4 with correct numbering of episodes and subtitles in SRT format?
It would be more convenient to watch with a video player.

**Comment by DerekPascarella** [comment]
I'm not going to revisit this patch to optimize subtitle timings. Sorry. Thank you for your input though.

Also, I am not authorized to release the SRTs. You can find the captured video all over YouTube though.
