### ISSUE TITLE
Crashes after pressing start on Redream emulator.

### ISSUE THREAD

**Issue by Sessh22** [DerekPascarella/BirdcageOfHorrors-EnglishPatchDreamcast#8]
Both the plain old restoration patch and this english patch both crash after pressing start at the title screen. The title is in english with that patch, but it hard crashes when you press start. Using the recent dev redream version. Happens with both standard and Japanese Cake bios. Used Universal Dreamcast Patcher 1.3, patcher says everything went smoothly.

Testing with original disc just hits the lockout message screen when pressing start, but no crash.

**Comment by DerekPascarella** [comment]
Redream is to blame. Either use Flycast, Demul, or NullDC.

Otherwise, there seems to be a Redream fix here: http://disq.us/p/3059vi6

**Comment by Sessh22** [comment]
Thanks I'll pass that on. Looking forward to watching.

**Comment by DerekPascarella** [comment]
You're welcome. Enjoy!

PS: A v1.1 release will be forthcoming to address typos found in the [issuse section](https://github.com/DerekPascarella/BirdcageOfHorrors-EnglishPatchDreamcast/issues).

**Comment by mSchul4** [comment]
I know the issue is closed, but I did manage to get it working on Redream. 
It only seems to work WITHOUT the retail BIOS. If it's being used, the games crash on pressing Start like in the report.
